name: Tailwind CSS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Create directories and files
      run: |
        mkdir -p src dist
        echo "@tailwind base;
        @tailwind components;
        @tailwind utilities;" > src/input.css
        
    - name: Initialize project and install dependencies
      run: |
        echo '{
          "name": "tailwind-build",
          "version": "1.0.0",
          "scripts": {
            "build": "tailwindcss -i ./src/input.css -o ./dist/output.css --minify"
          },
          "devDependencies": {
            "tailwindcss": "^3.0.0"
          }
        }' > package.json
        npm install
        
    - name: Build CSS
      run: |
        npm run build
        
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add dist/output.css
        git commit -m "Build Tailwind CSS" || echo "No changes to commit"
        git push origin || echo "No changes to push"