name: Tailwind CSS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install tailwindcss@latest
        
    - name: Create Tailwind config if not exists
      run: |
        if [ ! -f tailwind.config.js ]; then
          npx tailwindcss init
        fi
        
    - name: Create input.css if not exists
      run: |
        mkdir -p src
        echo "@tailwind base;" > src/input.css
        echo "@tailwind components;" >> src/input.css
        echo "@tailwind utilities;" >> src/input.css
        
    - name: Build CSS
      run: |
        mkdir -p dist
        npx tailwindcss -i src/input.css -o dist/output.css --minify
        
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add dist/output.css
        git diff --quiet && git diff --staged --quiet || git commit -m "Build Tailwind CSS"
        git push