name: Tailwind CSS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -D tailwindcss
        
    - name: Build CSS
      run: |
        npx tailwindcss -i src/input.css -o dist/output.css
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/output.css
        git commit -m "Build Tailwind CSS" || echo "No changes to commit"
        git push origin main || echo "No changes to push"
