name: Tailwind CSS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Project and Install Dependencies
      run: |
        npm init -y
        npm install --save-dev tailwindcss
        
    - name: Create Tailwind Files
      run: |
        mkdir -p src dist
        echo "@tailwind base;
        @tailwind components;
        @tailwind utilities;" > src/input.css
        npx tailwindcss init
        
    - name: Build Tailwind CSS
      run: |
        npx tailwindcss -i src/input.css -o dist/output.css --minify
        
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add dist/output.css
        git commit -m "Build Tailwind CSS" || echo "No changes to commit"
        git push origin || echo "No changes to push"